* VMware虚拟机组网模式
  安装VMware后，VMware会虚拟化10个交换机(vmnet0 - vmnet9)，同时在物理主机虚拟两块网卡(vmnet1, vmnet8)，利用这些虚拟交换机和物理主机虚拟网卡，物理主机和虚拟主机可以存在三种网络模式：
  1. 网桥模式(对应虚拟交换机vmnet0)
     VMware的虚拟交换机vmnet0通过网桥关联物理主机网卡，虚拟主机通过vmnet0交换机接入物理主机网卡关联网络。

          Router <---> vmnet0  |<---> 物理主机(物理网卡)
                               |<---> 虚拟主机(虚拟网卡)

     虚拟主机在物理主机原网段被视为一台独立的主机，可以与本网段其他主机互相访问，也可以通过Router访问外部网络。

  2. Host-Only模式(对应虚拟交换机vmnet1)
     物理主机通过虚拟网卡vmnet1，虚拟主机通过虚拟网卡，一起连接虚拟交换机vmnet1

          Route <---> (物理网卡)物理主机(虚拟网卡vmnet1) <---> vmnet1 <---> 虚拟主机(虚拟网卡)
                                                                      <---> 虚拟DHCP服务器(可选)

     虚拟主机和物理主机(虚拟网卡vmnet1)组成局域网，此时虚拟主机和物理主机可以互访，但物理主机原网段其他主机无法访问虚拟主机。

  3. NAT模式(对应虚拟交换机vmnet8)
     物理主机通过虚拟网卡vmnet8，虚拟主机通过虚拟网卡，一起连接虚拟交换机vmnet8

          Route <---> (物理网卡)物理主机(虚拟网卡vmnet8) <---> vmnet8 <---> 虚拟主机(虚拟网卡)
                             |                                   |
                             |--------------------------------虚拟NAT(提供DHCP服务、NAT和路由服务)

     虚拟主机和物理主机(虚拟网卡vmnet8)组成局域网，vmnet8交换机提供路由和NAT功能，此时虚拟主机和物理主机可以通过vmnet8交换机互访，而虚拟主机也可以通过虚拟NAT借道物理主机物理网卡访问外部网络。
     这种模式下，如果禁用物理主机(虚拟网卡vmnet8)，虚拟主机仍然可以访问外部网络，但物理主机无法访问虚拟主机。