* Bank Card
** Rule of NO.
    ISO标准的银行卡长度一般在13-19位，国际上也有12位的。
    银联标准的银行卡号一般是16位或者19位，双组织卡也有13-19位的。

    银行卡通常由如下三部分构成
    | xxxxxx          | xxxxxxxxxxxx        | x      |
    | 发卡行识别码6位 | 银行自定义位        | 校验位 |
    其中发卡行识别码以前叫做BIN码，由发卡行向ISO组织申请

*** BIN (Bank Identification Number)
    | VISA          |   4                        |        |
    | MASTER        |   51 - 55                  |        |
    | 银联标准卡    |   622126 - 622925          | 2004年 |
    |               |   620003 - 685800 (not all)| 2007年,申请了7002个62字头的卡BIN、1个638888，1个685800的卡BIN       |
    | 中国银行      |   601382                   | 长城卡       |
    | 交通银行      |   601428                   | 太平洋万事顺卡 |
    | 部分地方银行  |   603xxx                   |        |
    |深圳商业银行   |   602907                   | 2007年被平安收购合并为深圳平安银行  |
    | 北京银行      |   602969                   | 京卡   |
    | 仅国内使用    |   9                        |        |

    2000年，中国人民银行为推动联网通用工作，组织制定了一系列银行卡业务规范和技术标准。其中《银行卡发卡行标识代码及卡号》规定，在国内发行使用的各种人民币卡必须使用9字头BIN，但这种卡只能在国内使用，国际上不认。

    之后为了拓展国际市场，银联开始和VISA/MASTER合作，发行双标卡(银联+VISA或银联+MASTER)，在境内人民币走银联清算，在境外美元支付走VISA或MASTER清算，卡号也使用VISA或MASTER的BIN。但随着2004年银联申请到62开头BIN，以及人民币境内外清算资格的开放，境内卡在境外市场支付规模的扩大，银联开始要求国内银行只推单标卡，2015年央行规定，磁条卡升级到芯片卡必须使用PBOC3.0标准（VISA、万事达使用的EMV技术标准），新的单芯卡基本都是银联卡，到2017年起更是明确叫停双标卡，按照农行、中行等已逐渐出现的案例，银行将为双标卡持卡人换发两张卡：一张“62”开头的银联标准卡、一张境外卡组织的外币卡。

    目前BIN的名称已经被IIN(Issuer Identification Number)取代

*** Luhn algorithm
    Luhn算法，也称为“模10”算法，是一种简单的校验和（Checksum）算法，一般用于验证身份识别号码，例如信用卡号码、国际移动设备识别码（International Mobile Equipment Identity，缩写为IMEI），美国供应商识别号码，加拿大社会保险号码，以色列身份证号码，希腊社会安全号码等。

    Luhn算法在ISO/IEC 7812-1中定义，它不是一种安全的加密哈希函数，设计它的目的只是防止意外出错而不是恶意攻击，即我们常说的防君子不防小人。

    使用Luhn算法校验的步骤：
    1. 从右边第1个数字（校验数字位）开始往左数，所有的偶数位，其值乘以2(超过10则使用1+个位数)，作为该位的新值
    2. 基于偶数位的新值，对所有数字进行求和；
    3. 如果步骤2得到的总和模10为0，则校验通过。

** 银联标准卡的校验
    银联在其开放平台（https://open.unionpay.com/）提供了若干接口，其中就包括了银行卡信息查询（https://open.unionpay.com/tjweb/api/detail?apiSvcId=51）接口，该接口可以根据银行卡卡号，返回发卡行、发卡行机构代码、卡性质、卡类别、卡种、卡品牌、卡产品、卡等级、卡介质、所属总行机构中文名称、所属总行机构中文简称。

    该平台提供了另外一个优秀的接口，验证银行卡信息（https://open.unionpay.com/tjweb/api/detail?apiSvcId=21）。我们可以通过以下5种方式进行验证，灵活组合，按需选择：
    + 两要素：银行卡号+姓名
    + 两要素：银行卡号+身份证号
    + 三要素：银行卡号+姓名+身份证号
    + 四要素：银行卡号+姓名+身份证号+银行预留手机号
    + 六要素：银行卡号+姓名+身份证号+银行预留手机号+CVN2+有效期
    推荐借记卡使用四要素验证，贷记卡使用六要素验证

** 系统设计方案
    1. 在用户输入银行卡时，使用Luhn算法进行初步校验
    2. 银行预留手机号的校验
    3. 调用银行卡信息查询接口(调用这个接口，一方面可以积累数据，另一方面可以确定客户的银行卡性质，是借记卡还是贷记卡)
    4. 调用验证银行卡信息接口

    信息安全存储：
    + 银行卡号，身份证号，手机号，建议加密存储
    + 借记卡密码，贷记卡CVN2、有效期，建议不存储
    + 数据安全存储，不单单指数据库，建议肉眼可见的介质之上都做安全存储，比如应用程序日志、数据同步文件等
    + 数据传输过程中，理应也如此，银联接口中CVN2、有效期就要求RSA加密



