* most common conjunction

after
  During the period of time following (an event)
    bath time ended in a flood after the taps were left running

although
  In spite of the fact that; even though.
    although the sun was shining, it wasn't that warm.

and
  Used to connect words of the same part of speech, clauses, or sentences, that are to be taken jointly.
    they can read and write.

as
  Used to indicate that something happens during the time when something else is taking place.
    as she grew older, she kept more to herself.

  Used to indicate by comparison the way that something happens or is done.
    they can do as they wish

  Because; since.
    I must stop now as I have to go out

  Even though.
    sweet as he is, he doesn't pay his bills

because
  For the reason that; since.
    we did it because we felt it our duty.
  [informal] Used to introduce a word or phrase that stands for a clause expressing an explanation or reason.
    making a bag of popcorn with hot sauce for lunch because hungry

before
  During the period of time preceding (a particular event or time)
    they lived rough for four days before they were arrested

  In preference to; rather than.
    they would die before they would cooperate with each other

but
  Used to introduce a phrase or clause contrasting with what has already been mentioned.
    this is one principle, but it is not the only one

  Used after an expression of apology for what one is about to say.
    I'm sorry, but I can't pay you

  [with negative or in questions] Used to indicate the impossibility of anything other than what is being stated.
    there was nothing they could do but swallow their pride

either or
  Used before the first of two (or occasionally more) given alternatives (the other being introduced by ‘or’)
    either I accompany you to your room or I wait here

except
  Used before a statement that forms an exception to one just made
    I didn't tell him anything, except that I needed the money
    our berets were the same except mine was blue

for
  [literary] Because; since.
    he felt guilty, for he knew that he bore a share of responsibility for Fanny's death

if
  (introducing a conditional clause) on the condition or supposition that; in the event that.
    if you have a complaint, write to the director

  Despite the possibility that; no matter whether
    if it takes me seven years, I shall do it

  (often used in indirect questions) whether.
    he asked if we would like some coffee

  [with modal] Expressing a polite request.
    if I could just use the phone, I'll get a taxi

like [informal]
  In the same way that; as.
    people who change countries like they change clothes

  As though; as if.
    I felt like I'd been kicked by a camel

neither nor
  Used before the first of two (or occasionally more) alternatives (the others being introduced by ‘nor’) to indicate that they are each untrue or each does not happen.
    I am neither a liberal nor a conservative
    the sheets were never washed, nor the towels, nor his shirts

now
  As a consequence of the fact.
    now you mention it, I haven't seen her around for ages

once
  As soon as; when.
    once the grapes were pressed, the juice was put into barrels

or
  Used to link alternatives.
    a cup of tea or coffee

  Otherwise (used to introduce the consequences of something not being done or not being the case)
    hurry up, or you'll miss it all

plus
  [informal] Furthermore; also.
    it's packed full of medical advice, plus it keeps you informed about the latest research

provided (that)
providing (that)
  On the condition or understanding that.
    cutting corners was acceptable, provided that you could get away with it

since
  For the reason that; because.
    delegates were delighted, since better protection of rhino reserves will help protect other rare species

so
  And for this reason; therefore.  (so that)
    it was still painful so I went to see a specialist
    it was overgrown with brambles, so that I had difficulty making any progress

  With the aim that; in order that (so that)
    they whisper to each other so that no one else can hear

that
  Introducing a subordinate clause expressing a statement or hypothesis.
    she said that she was satisfied
    it is possible that we have misunderstood

    he seemed pleased that I wanted to continue
    she was so tired that she couldn't think

though
  Despite the fact that; although.
    though they were speaking in undertones, Percival could hear them
  [with modal] Even if (introducing a possibility)
    you will be informed of its progress, slow though that may be
  However; but (introducing something opposed to or qualifying what has just been said)
    her first name was Rose, though no one called her that

unless
  Except if (used to introduce the case in which a statement being made is not true or valid)
    unless you have a photographic memory, repetition is vital

until
  Up to (the point in time or the event mentioned)
    you don't know what you can achieve until you try

than
  Used in expressions introducing an exception or contrast. (rather than)
    they observe rather than act

  Used in expressions indicating one thing happening immediately after another.
    scarcely was the work completed than it was abandoned

till
  less formal way of saying until

when
  At or during the time that.
    I loved maths when I was at school
  After
    call me when you've finished
  At any time that; whenever.
    can you spare five minutes when it's convenient?

  After which; and just then (implying suddenness)
    he had just drifted off to sleep when the phone rang

  In view of the fact that; considering that.
    why bother to paint it when you can photograph it with the same effect?

  Although; whereas.
    I'm saying it now when I should have told you long ago

whenever
  At whatever time; on whatever occasion (emphasizing a lack of restriction)
    you can ask for help whenever you need it
  Every time that.
    the springs in the armchair creak whenever I change position

whereas
  In contrast or comparison with the fact that.
    you treat the matter lightly, whereas I myself was never more serious

wherever
  In every case when.
    use wholegrain breakfast cereals wherever possible

whether
  Expressing a doubt or choice between alternatives.
    he seemed undecided whether to go or stay
  Indicating that a statement applies whichever of the alternatives mentioned is the case.
    I'm going whether you like it or not

while
  During the time that; at the same time as.
    nothing much changed while he was away

  Whereas (indicating a contrast)
    one person wants out, while the other wants the relationship to continue
  In spite of the fact that; although.
    while I wouldn't recommend a night-time visit, by day the area is full of interest

yet
  But at the same time; but nevertheless.
  the path was dark, yet I slowly found my way







