* IPv4 Address
  IPv4 (4B, 32bit)，采用4组(0-255)的数字表示，如：192.168.0.1，最多可以有2的32次方，40亿个地址。
  地址由两部分组成：network id + host id，通过Subnet Mask可以精确地区分两者。

** 公网 IP
  根据Subnet的范围，国际组织将IP Address分为几大类：
  + A类地址，0(1bit) + network id(7bit) + host id(24bit)，Subnet Mask:255.0.0.0
    network id取值范围为 0.0.0.0/8 到 127.0.0.0/8 (其中0和127不可用)。每个network下约有1亿六千万host。
  + B类地址, 10(2bit) + network id(14bit) + host id(16bit), Subnet Mask:255.255.0.0
    network id取值范围为 128.0.0.0/16 到 191.255.0.0/16，每个network下约有六万五千host
  + C类地址，110(3bit) + network id(21bit) + host id(8bit), Subnet Mask:255.255.255.0
    network id取值范围为 192.0.0.0/24 到 223.255.255.0/24，每个network下有256-2台host
  + D类地址，1110(4bit) + 多播组号(28bit)，不区分网络号和主机号
    IP地址的范围为224.0.0.0-239.255.255.255，主要用于各种组播
  + E类地址, 11110(5bit) + 保留号(27bit)，留作后用
    IP地址的范围为240.0.0.0-255.255.255.255

** 特殊 IP
  对于A、B、C三类由network id + host id组成的 IP地址，有如下约定：
  1. host id 全为0的IP，即为其network id
  2. host id 全为1的IP，对应该network的广播IP
  3. 以127开头的A类地址，作为本机loopback地址，不会被网卡广播

  另外在每类地址中，保留了部分网段用做特殊用途，如以下示例：(所有保留网段可以参考wiki-ipv4)
  + private network
  来自私有地址的数据包在互联网上不会被路由器转发。这些私有地址主要用于企业、家庭局域网使用，必须通过NAT才能访问互联网，
  | 10.0.0.0/8     |  10.0.0.0 ~ 10.255.255.255    |          |
  | 172.16.0.0/12  | 172.16.0.0 ~ 172.31.255.255   |          |
  | 192.168.0.0/16 | 192.168.0.0 ~ 192.168.255.255 |          |
  | 100.64.0.0/10  | 100.64.0.0 ~ 100.127.255.255  |  ISP NAT |

** LAN中使用公网网络号的影响
  如果在局域网中使用公网网络号，除非不需要访问互联网，否则会和实际公网冲突，导致LAN无法访问互联网上该网段。

** 子网划分
  对于分配的某个网段，可以通过调整Subnet Mask来借用主机号作为子网络号，在该网段下进一步划分子网，好处是：
  1. 单位内各部门可以隔离网段
  2. 合理划分子网段，防止少量主机占用网段，造成浪费



